// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Kezlubr3Jafx9aHs8jU6jy3bepHc4FA',
    appId: '1:761960934903:web:edf39f7d381160857b52f2',
    messagingSenderId: '761960934903',
    projectId: 'homebakes-e9e3b',
    authDomain: 'homebakes-e9e3b.firebaseapp.com',
    storageBucket: 'homebakes-e9e3b.appspot.com',
    measurementId: 'G-GV3RT0SQDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhojeF4kVsfZBITII6MqhpIzOLTPgiJ0',
    appId: '1:761960934903:android:2a7168f39d2d63a77b52f2',
    messagingSenderId: '761960934903',
    projectId: 'homebakes-e9e3b',
    storageBucket: 'homebakes-e9e3b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Kezlubr3Jafx9aHs8jU6jy3bepHc4FA',
    appId: '1:761960934903:web:adadf0e2a8096e217b52f2',
    messagingSenderId: '761960934903',
    projectId: 'homebakes-e9e3b',
    authDomain: 'homebakes-e9e3b.firebaseapp.com',
    storageBucket: 'homebakes-e9e3b.appspot.com',
    measurementId: 'G-NPSRWD4QFW',
  );

}